## Numpy
- 선형대수, 행렬 수치연산과 관련된 라이브러리
- 문과생, 고졸, 전문대졸...선형대수가 뭐예영?
 + 선형대수 공부해야함?

- NumPy를 기반으로 => 통계, 머신러닝, 등등
- 

In [1]:
import numpy as np
print(np.__version__)

1.26.2


In [2]:
num1 = [1,2,3,4]
num2 = [3,4,5,6]

arr1 = np.array(num1)
arr2 = np.array(num2)

arr1 + arr2

array([ 4,  6,  8, 10])

In [3]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [4]:
a1.dtype

dtype('int32')

In [5]:
np.array([0.5, 2, 0.01, 8]).dtype

dtype('float64')

In [6]:
np.arange(0,10,2)
np.arange(1,10)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
np.arange(12).reshape(4,1,3)

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [11]:
b1 = np.arange(12).reshape(2,2,3)
b1.shape

(2, 2, 3)

In [12]:
b2 = np.arange(5)
b2.shape

(5,)

In [13]:
# 범위의 시작과 끝 정해서 배열 생성
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [18]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [21]:
# 단위 행렬
arr_I = np.eye(3)
arr_I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr_I.shape

(3, 3)

In [24]:
np.array(['1.5', '0.62']) #데이터 형변환

array(['1.5', '0.62'], dtype='<U4')

In [25]:
#astype() # pandas에서 사용가능 
arr = np.array(['1.5', '0.62'])
num_arr = arr.astype(float)
num_arr

array([1.5 , 0.62])

In [26]:
np.array(['1.5', '0.62'], dtype = float)

array([1.5 , 0.62])

In [27]:
num_f1 = np.array([10,21,0.549,4.75,5.98])
num_f1 = num_f1.astype(int)
num_f1

array([10, 21,  0,  4,  5])

In [28]:
num_f1 = np.array([10,21,0.549,4.75,5.98])
num_f1 = num_f1.astype(float)
num_f1

array([10.   , 21.   ,  0.549,  4.75 ,  5.98 ])

In [33]:
# 난수 - 무작위로 숫자를 추출한다.
np.random.rand(2,3) #0에서 1사이의 실수 난수를 갖음

array([[0.57560978, 0.98879202, 0.45379851],
       [0.30161489, 0.00327753, 0.83761873]])

In [35]:
np.random.randint(1,100, 10).reshape(2,5)

array([[84, 96, 96, 82, 39],
       [81, 14, 38, 51, 67]])

In [43]:
numbers = []
cnt = 0

while True:
    num = np.random.randint(1,46)
    
    if cnt == 6:
        numbers.sort()
        numbers.append("+")
    elif cnt == 7:
        break
        
    if num in numbers:
        continue
    else:
        numbers.append(num)
        cnt+=1
        continue

print(numbers)

[6, 17, 26, 36, 37, 39, '+', 27]


## 배열의 연산


In [44]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1,2,3,4])

# 덧셈
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


## 비교 연산

In [46]:
arr1 > 20

array([False, False,  True,  True])

## 통계 연산
- NumPy, 합, 평균, 표준 편차, 분산, 최솟값, 최댓값, 누적 합, 누적 곱 메서드가 존재한다.
  + 기술통계량 : 현재 데이터 상태를 표현(=묘사, Describe)한다.
- 통계 : 평균이 전부다! (Mean is Everything!)
  + 모수 통계
  + 비모수 통계
  + 베이지안 통계

In [48]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [49]:
arr3.sum()

10

In [50]:
arr3.mean()

2.0

In [51]:
arr3.std() # 표준편차

1.4142135623730951

In [53]:
arr3.var() #분산

2.0

## 누적합과 누적곱
- cumsum() : 누적합
- cumprod() : 누적곱

In [54]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

## 배열의 인덱싱과 슬라이싱
- string, list, tuple과 동일한 방법으로 접근

In [55]:
 a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [56]:
a1[0]

0

In [57]:
a1[4]

40

In [58]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [59]:
a1[[0, 2,4]]

array([ 0, 20, 40])

In [61]:
a2 = np.arange(10, 100, 10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [62]:
a2[0][0]

10

In [63]:
a2[0,1]

20

## 배열 조건문
- pandas 문법과 유사하다

In [64]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [65]:
a[a>3]

array([4, 5, 6])

In [68]:
a[a%2 == 0]

array([2, 4, 6])

## 배열의 슬라이싱



In [69]:
b1 = np.array([0,1,2,3,4,5])
b1[1:4]

array([1, 2, 3])

In [70]:
b1[2:5] = np.array([25, 35,45])
b1

array([ 0,  1, 25, 35, 45,  5])

In [71]:
b1[3:6] = 60
b1

array([ 0,  1, 25, 60, 60, 60])

In [72]:
b2 = np.arange(10, 100, 10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [73]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [74]:
b2[1:3][1:3]

array([[70, 80, 90]])

## NumPy 조건문
- np.where : 단일 조건문
- np.select : 다중 조건문

In [75]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
# 0,1,2,3,4,50,60,70,80,90
np.where(arr < 5, arr, arr * 10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [77]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
# 100,101,2,3,4,5,12,14,16,18
cond_list = [arr> 5, arr<2]
choice_list = [arr * 2, arr + 100]
np.select(cond_list, choice_list, default = arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])